apiVersion: v1
kind: Service
metadata:
  name: {{.Name}}
{{if IsEven 1}}
  labels:
    service.kubernetes.io/service-proxy-name: foo
{{end}}
spec:
  selector:
    svc: {{.Name}}
  ports:
  - port: 80
    targetPort: 80
